'use client'

export default function Overview() {
    return (
        <div className="flex flex-col items-center justify-center px-8 py-16">
            <div className="w-full text-center mb-7">
                <h3 className="mt-3.5 text-3xl font-bold text-blue-500">Metabolic Networks Features</h3>
                <p className="xl:w-2/3 mt-3.5 mx-auto font-medium">Including all features of T2DM extracted from GTEx patient data and specific tissues (T2DM & Liver - Pancreas).</p>
            </div>
            <div className="xl:w-3/4 space-y-4 text-justify bg-white p-8 rounded-2xl shadow-xl">
                <section>
                    <h2 className="font-bold">Met2MetGraph</h2>
                    <p>This repository contains metabolic network features extracted from sample patient data, including Type 2 Diabetes Mellitus (T2DM)-related tissue data and liver-pancreas tissue data. The repository is divided into two main sections:</p>
                    <ol className="list-decimal list-inside ps-4 font-bold">
                        <li>T2DM Features</li>
                        <li>Liver Features</li>
                    </ol>
                    <p>Each section includes features organized into the following schemes:</p>
                    <ol className="list-decimal list-inside ps-4">
                        <li><b>MetGraph</b>: Original features derived from metabolic networks.</li>
                        <li><b>NDD (Node Distance Dependency)</b>: Features based on the distance relationships among metabolites.</li>
                        <li><b>TM1</b>: First-order random walk features originating from specific metabolites and their immediate neighbors.</li>
                        <li><b>TM2</b>: Second-order random walk features capturing broader metabolite neighborhood structures.</li>
                        <li><b>NDD+TM1</b>: Combined features incorporating both NDD and first-order random walks.</li>
                        <li><b>NDD+TM1+TM2</b>: Integrated features combining NDD, TM1, and TM2.</li>
                    </ol>
                </section>
                <section>
                    <h2 className="font-bold">Graph Embedding</h2>
                    <p>We employ several graph embedding algorithms, including:</p>
                    <ol className="list-decimal list-inside ps-4 font-bold">
                        <li>Graph2Vec</li>
                        <li>GL2Vec</li>
                        <li>FeatherGraph</li>
                        <li>Netpro2Vec</li>
                    </ol>
                    <p>These embeddings are generated using <b>MetGraph</b> features as the primary input source. The features within are generated by combining four patient groups (100, 200, 300, 400), two threshold settings (1_80 and 2_80), three aggregation schemes (MeanSum, MinMax, MinSum), and three embedding dimensions (64, 128, 196). So, we have 72 features within FeatherGraph, GL2Vec, Graph2Vec, and several Netpro2vec in total.</p>
                </section>
            </div>
        </div>
    );
}